version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - NB_UID=1000
      - NB_GID=100
      - GEN_CERT=yes
      - GRANT_SUDO=yes
    user: root
    command: start.sh jupyter lab